name: Nuget Package Publish

run-name: ${{ github.actor }} is running Nuget Publish

on:
  pull_request:
    branches:
      - master

env:
  POLYGON_TOKEN: ${{ secrets.POLYGON_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'
      - run: |
          dotnet clean
          dotnet restore
          dotnet build

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'
      - run: |
          dotnet test