name: Nuget Package Publish

run-name: ${{ github.actor }} is running Nuget Publish

on: [push]

env:
  POLYGON_TOKEN: ${{ secrets.POLYGON_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'
      - run: |
          dotnet clean
          dotnet restore
          dotnet build

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'
      - run: |
          dotnet test

  publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Package
        run: dotnet pack

      - name: Publish Client
        run: |
          dotnet nuget push ./Polygon.Client/bin/Release/*.nupkg  \
            -k $NUGET_AUTH_TOKEN \
            -s https://api.nuget.org/v3/index.json \
            --skip-duplicate
    
    env:
      NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}