name: Nuget Package Publish

run-name: ${{ github.actor }} is running Nuget Publish

on: [push]

env:
  POLYGON_TOKEN: ${{ secrets.POLYGON_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            dotnet: ['2.1.x', '6.0.x', '8.0.x']
    name: Dotnet ${{ matrix.dotnet }} build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - run: |
          dotnet clean
          dotnet restore
          dotnet build

  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
        matrix:
            dotnet: ['2.1.x', '6.0.x', '8.0.x']
    name: Dotnet ${{ matrix.dotnet }} test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '${{ matrix.dotnet }}'
      - run: |
          dotnet test

  publish_clients_prerelease:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '2.1.x'
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            clients:
              - './Polygon.Client/**'
            dependencyinjection:
              - './Polygon.Client.DependencyInjection/**'
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '2.1.x'

      - name: Package
        run: dotnet pack

      - name: Publish Client
        if: steps.filter.outputs.clients == 'true'
        run: |
          dotnet nuget push ./Polygon.Client/bin/Release/*.nupkg  \
            -k $NUGET_AUTH_TOKEN \
            -s https://api.nuget.org/v3/index.json \
            --skip-duplicate
      - name: Skip Publish Client
        if: steps.filter.outputs.clients != 'true'
        run: echo "No Polygon.Client changes - Skipping Publish."
    
      - name: Publish DependencyInjection
        if: steps.filter.outputs.clients == 'true'
        run: dotnet nuget push ./Polygon.Client.DependencyInjection/bin/Release/*.nupkg \
          -k $NUGET_AUTH_TOKEN \
          -s https://api.nuget.org/v3/index.json \
          --skip-duplicate
      - name: Skip Publish DependencyInjection
        if: steps.filter.outputs.clients != 'true'
        run: echo "No Polygon.Client.DependencyInjection changes - Skipping Publish."
    
    env:
      NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}

  # publish_release:
  #   runs-on: ubuntu-latest